package com.engseen.erp.service.dto;

import lombok.Data;
import lombok.ToString;

import java.math.BigDecimal;
import java.util.Date;

@Data
@ToString
public class ItemMasterDTO {
    private int id;
    private String item;
    private String itemDescription;
    private String unitOfMeasure;
    private String revisionLevel;
    private Character makeBuyCode;
    private Character itemType;
    private Character itemStatus;
    private Character lotTrace;
    private Character serialization;
    private Character orderPolicy;
    private Character inspectionRequired;
    private String drawing;
    private Character itemClassifications;
    private String reference1;
    private String reference2;
    private String reference3;
    private String reference4;
    private BigDecimal itemShippingWeight;
    private BigDecimal itemShippingVolumn;
    private String itemPackageType;
    private BigDecimal itemPiecesPerPackage;
    private BigDecimal itemGrossWeight;
    private Character lotAssignmentPolicy;
    private Character lotDefaultPolicy;
    private Character fIFOInventoryPolicy;
    private Character backflushPolicy;
    private Integer availableCalendarDays;
    private Integer shelfLifeCalendarDays;
    private Integer retestCalendarDays;
    private Integer lastLot;
    private String lotMask;
    private String defaultLot;
    private Character lotCounter;
    private String serialNumberMask;
    private String defaultSerialNumber;
    private Character serialNumberCounter;
    private String plannerBuyer;
    private Integer runLeadTime;
    private Integer fixedLeadTime;
    private Integer inspectionLeadTime;
    private Integer planLeadTime;
    private Integer lotSizeDay;
    private BigDecimal lotSizeQuantity;
    private BigDecimal safetyStock;
    private BigDecimal minimumLotSize;
    private BigDecimal multipleLotSize;
    private String preferredStoreNo;
    private String preferredStoreBin;
    private Character forecastCode;
    private Character forecastPeriod;
    private Integer itemYieldFactor;
    private Integer decimalPrecisionCode;
    private Integer lowLevelCode;
    private String remark1;
    private String remark2;
    private String remark3;
    private String inventoryAccountNo;
    private String salesAccountNo;
    private String cOGSAccountNo;
    private BigDecimal averageSellingPrice;
    private Integer costCode;
    private BigDecimal materialCost;
    private BigDecimal laborCost;
    private BigDecimal variableOverheadCost;
    private BigDecimal fixedOverheadCost;
    private BigDecimal totalCost;
    private BigDecimal rolledMaterialCost;
    private BigDecimal rolledLaborCost;
    private BigDecimal rolledVariableOverheadCost;
    private BigDecimal rolledFixedOverheadCost;
    private BigDecimal totalRolledCost;
    private BigDecimal standardUnitPrice;
    private String label1;
    private String label2;
    private BigDecimal minimumSellingPrice;
    private Integer lastSerialNumber;
    private Integer mRPPriority;
    private Date created;
    private String createdBy;
    private Date modified;
    private String modifiedBy;
    private Date accessed;
    private String accessedBy;
}
